<script type="text/javascript">
    jQuery(document).ready(function () {
        jQuery('#dyntable2').dataTable({
            "bScrollInfinite": true,
            "bScrollCollapse": true,
            "sScrollY": "300px",
            "sDom": '<"toolbar">frti'
                    //"sDom": '<"toolbar">frti<"pag">'
        });

        jQuery("div.toolbar").html('<a href="<?php echo $this->url('repository/algorithms', array('action' => 'new')) ?>"><img src="<?php echo $this->basePath() . '/images/table_add.png'; ?>" /></a>');
        //jQuery("div.pag").html('<?php #echo $this->paginationControl($this->data, 'Sliding', 'partials/paginator');                ?>');
    });
</script>
<style>
    .toolbar {
        float:left;
    }
    .toolbar img {
        padding: 5px 0 0 7px;
        vertical-align: text-top;
    }
</style>
<div class="row">
    <h4 class="widgettitle">Categorias</h4>
    <table id="dyntable2" class="table table-striped table-bordered table-infinite">
        <colgroup>
            <col class="con0" style="align: center; width: 4%" />
            <col class="con1" style="align: center; width: 25%"/>
            <col class="con0" style="align: center; width: 25%"/>
            <col class="con1" style="align: center; width: 20%"/>
            <col class="con0" style="align: center; width: 10%"/>
            <col class="con1" style="align: center; width: 6%"/>
        </colgroup>
        <thead>
            <tr>
                <th class="head0">Id</th>
                <th class="head1">Nome</th>
                <th class="head1">Categoria</th>
                <th class="head1">Desenvolvedor</th>
                <th class="head1">Data Criação</th>
                <th class="head0 nosort">Ações</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($this->data as $entity): ?>
                <tr class="gradeX">
                    <td><?php echo $entity->getId() ?></td>
                    <td><?php echo $entity->getTitle() ?></td>
                    <?php foreach ($this->categories as $category) : ?>
                        <?php if ($category->getId() == $entity->getCategoryId()): ?>
                            <td><?php echo $category->getName(); ?></td>
                            <?php break; ?>
                        <?php endif; ?>
                    <?php endforeach; ?>
                    <td><?php echo $entity->getDeveloper() ?></td>
                    <td><?php echo $entity->getCreatedAt() ?></td>
                    <td>
                        <a title="Adicionar Código" href="<?php echo $this->url('repository/algorithms/code', array('action' => 'new', 'id' => $entity->getId())) ?>"><img src="<?php echo $this->basePath() . '/images/code_add.png'; ?>" height="16px" /></a>
                        <a title="Editar" href="<?php echo $this->url('repository/algorithms', array('action' => 'edit', 'id' => $entity->getId())) ?>"><img src="<?php echo $this->basePath() . '/images/table_edit.png'; ?>" height="16px" /></a>
                        <a title="Apagar" href="<?php echo $this->url('repository/algorithms', array('action' => 'delete', 'id' => $entity->getId())) ?>"><img src="<?php echo $this->basePath() . '/images/table_delete.png'; ?>" height="16px" /></a>
                    </td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
    <br>

    <?php echo $this->paginationControl($this->data, 'Sliding', 'partials/paginator'); ?>



</div>