-- MySQL Script generated by MySQL Workbench
-- 07/12/16 12:39:13
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema sycorax
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `sycorax` ;

-- -----------------------------------------------------
-- Schema sycorax
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sycorax` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `sycorax` ;

-- -----------------------------------------------------
-- Table `sycorax`.`category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sycorax`.`category` ;

CREATE TABLE IF NOT EXISTS `sycorax`.`category` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `sycorax`.`Algorithms`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sycorax`.`Algorithms` ;

CREATE TABLE IF NOT EXISTS `sycorax`.`Algorithms` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `category_id` INT UNSIGNED NOT NULL,
  `hash` VARCHAR(255) NOT NULL,
  `title` VARCHAR(255) NOT NULL,
  `developer` VARCHAR(255) NOT NULL,
  `description` VARCHAR(255) NOT NULL,
  `createdAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Algorithms_category_idx` (`category_id` ASC),
  UNIQUE INDEX `hash_UNIQUE` (`hash` ASC),
  CONSTRAINT `fk_Algorithms_category`
    FOREIGN KEY (`category_id`)
    REFERENCES `sycorax`.`category` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sycorax`.`Code`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sycorax`.`Code` ;

CREATE TABLE IF NOT EXISTS `sycorax`.`Code` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Algorithms_id` INT UNSIGNED NOT NULL,
  `language` VARCHAR(255) NOT NULL,
  `version` VARCHAR(255) NOT NULL,
  `code` TEXT NOT NULL,
  `createdAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Code_Algorithms1_idx` (`Algorithms_id` ASC),
  CONSTRAINT `fk_Code_Algorithms1`
    FOREIGN KEY (`Algorithms_id`)
    REFERENCES `sycorax`.`Algorithms` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
