<?php echo $this->doctype(); ?>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>
        <?php echo $this->headTitle('Repositorio de Codigo Versao 0.1'); ?>

        <!-- Le styles -->
        <?php
        echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                # Style Default
                ->appendStylesheet($this->basePath() . '/css/style.default.css')
                ->appendStylesheet($this->basePath() . '/css/style.palegreen.css')
                # File Upload
                ->appendStylesheet($this->basePath() . '/css/bootstrap-fileupload.min.css')
                # TimePicjer
                ->appendStylesheet($this->basePath() . '/css/bootstrap-timepicker.min.css')
                # Custom
                ->appendStylesheet($this->basePath() . '/css/custom.css')
        ;
        ?>

        <!-- Scripts -->
        <?php
        echo $this->headScript()
                # Jquery
                ->appendFile($this->basePath() . '/js/jquery-1.10.2.min.js')
                ->appendFile($this->basePath() . '/js/jquery-migrate-1.2.1.min.js')
                ->appendFile($this->basePath() . '/js/jquery-ui-1.10.3.min.js')
                # bootstrap
                ->appendFile($this->basePath() . '/js/bootstrap.min.js')
                # Modernirz
                ->appendFile($this->basePath() . '/js/modernizr.min.js')
                # Cookies
                ->appendFile($this->basePath() . '/js/jquery.cookies.js')
                # Uniform
                ->appendFile($this->basePath() . '/js/jquery.uniform.min.js')
                # FileUpload
                ->appendFile($this->basePath() . '/js/bootstrap-fileupload.min.js')
                # TimePicker
                ->appendFile($this->basePath() . '/js/bootstrap-timepicker.min.js')
                # Validate
                ->appendFile($this->basePath() . '/js/jquery.validate.min.js')
                # TagsInput
                ->appendFile($this->basePath() . '/js/jquery.tagsinput.min.js')
                # Autogrow
                ->appendFile($this->basePath() . '/js/jquery.autogrow-textarea.js')
                # charCount
                ->appendFile($this->basePath() . '/js/charCount.js')
                # ColorPicker
                ->appendFile($this->basePath() . '/js/colorpicker.js')
                # Spinner
                ->appendFile($this->basePath() . '/js/ui.spinner.min.js')
                # Chosen Jquery
                ->appendFile($this->basePath() . '/js/chosen.jquery.min.js')
                # Slimscroll
                ->appendFile($this->basePath() . '/js/jquery.slimscroll.js')
                # Custom
                ->appendFile($this->basePath() . '/js/custom.js')
                # Forms
                ->appendFile($this->basePath() . '/js/forms.js')

        ;
        ?>
    </head>
    <body>
        <div id="mainwrapper" class="mainwrapper">
            <div class="header">
                <div class="logo">
                    <a class="logo" href="dashboard.html">Algorithms</a>
                </div>
                <div class="headerinner">
                    <ul class="headmenu">
                        <?php echo $this->menuNavigation($this->menu, $this->basePath() . '/repository'); ?>
                    </ul><!--headmenu-->
                </div>
            </div>

            <div class="leftpanel">

                <div class="leftmenu">        
                    <ul class="nav nav-tabs nav-stacked">
                        <li class="nav-header">Categorias</li>
                        <?php echo $this->menuCategory($this->categories, $this->basePath() . '/repository/algorithms/item'); ?>                          
                    </ul>
                </div><!--leftmenu-->

            </div><!-- leftpanel -->

            <div class="rightpanel">

                <div class="pageheader">
                    <div class="pageicon"><span class="<?php echo $this->headerIconName; ?>"></span></div>
                    <div class="pagetitle">
                        <h5><?php echo $this->headerSubTitle; ?></h5>
                        <h1><?php echo $this->headerTitle; ?></h1>
                    </div>
                </div><!--pageheader-->

                <div class="maincontent">
                    <div class="maincontentinner">

                        <?php echo $this->content; ?>


                    </div><!--maincontentinner-->
                </div><!--maincontent-->

            </div><!--rightpanel-->

        </div><!--mainwrapper-->
        <?php #echo $this->inlineScript()  ?>
    </body>
</html>